### PR TITLE
Enable automatic stackgres upgrades

### PR DESCRIPTION
**Pull request by zugao**
## Checklist

- [x] The PR has a meaningful title. It will be used to auto generate the
      changelog.
      The PR has a meaningful description that sums up the change. It will be
      linked in the changelog.
- [x] PR contains a single logical change (to build a better changelog).
- [x] Categorize the PR by adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog.
- [ ] Link this PR to related issues or PRs.

### CODE REVIEW

**Review by wejdross — CHANGES_REQUESTED** [review]
I'd rather have a recurring ticket than working with `:latests` version of software, we need to take into consideration that Stackgres might introduce breaking changes and we will be in huge problem as Operator will perform installation on all possible clusters at once - imagine breaking change that was release in USA during Your night OnCall and on 3 AM You have all possible clusters affected with some hellish change.

**Review by TheBigLee — APPROVED** [review]

**Comment by TheBigLee** [comment]
> I'd rather have a recurring ticket than working with `:latests` version of software, we need to take into consideration that Stackgres might introduce breaking changes and we will be in huge problem as Operator will perform installation on all possible clusters at once - imagine breaking change that was release in USA during Your night OnCall and on 3 AM You have all possible clusters affected with some hellish change.

I would rather go with the approach of setting all non-prod clusters to the `fast` channel
There we have the updates earlier and would see any breaking changes or problems with newer version.

**Comment by Kidswiss** [comment]
> > I'd rather have a recurring ticket than working with `:latests` version of software, we need to take into consideration that Stackgres might introduce breaking changes and we will be in huge problem as Operator will perform installation on all possible clusters at once - imagine breaking change that was release in USA during Your night OnCall and on 3 AM You have all possible clusters affected with some hellish change.
> 
> I would rather go with the approach of setting all non-prod clusters to the `fast` channel There we have the updates earlier and would see any breaking changes or problems with newer version.

Yes, I like that idea.

**Review by wejdross — APPROVED** [review]
Please follow BigLee's idea and I'm happy as well :D

**Pull request merged**
