### PR TITLE
Add composition for MySQL

### PR DESCRIPTION
**Pull request by susana-garcia**
## Summary
- Adds composition for exoscale mysql database.
- Adds golden test.
- Adds commodore config parameters to docs.

## Checklist

- [X] PR contains a single logical change (to build a better changelog).
- [X] Update the documentation.
- [X] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog.
- [X] Link this PR to related issues or PRs.

### CODE REVIEW

**Review by ccremer — APPROVED** [review]
Diff LGTM, I didn't test anything

**Comment by susana-garcia** [comment]
@ccremer quick question: how do you usually test it? running the integration tests and component tests or do you use another approach as well?

**Comment by ccremer** [comment]
Currently we don't have yet engineered a test infrastructure in the local env in this repo, even though we install kind-cluster and even crossplane, but not with providers installed.
So, atm we test the composition during deployment to lab cluster and iron out issues in the separate deployment story. So in sense it's fine to not further test it here resp. only manually inspect the golden files.

**Comment by susana-garcia** [comment]
ok, I see, thank you for the feedback

**Review by ZuGao — APPROVED** [review]
LGTM

**Pull request merged**
